@startuml
' Colors:
' - Default color for interfaces
' - blue color for specific classes
' - green for external objects
' Relationships:
' <|-- Inheritance
' *--> Ownership
' --> Reference
' ..> Call

object MessageLifecycleHandler {

}

object MessagesAPI {
  IWantToDisplayMessage(handler, webcontents):token
}

object ConfirmMessage


MessageLifecycleHandler <|-- ConfirmMessage

@enduml